version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: infrastructure/
      - terraform/validate:
          path: infrastructure/
      - terraform/plan:
          path: infrastructure/
      - terraform/apply:
          path: infrastructure/
      - terraform/destroy:
          path: infrastructure/
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - aws-cli-cred-setup:
          context: aws
      - single-job-lifecycle